services:
  redis: 
    image: redis:7.2-bookworm
    expose:
      - 6379
    networks:
      - redis-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s
    restart: always

networks:
  redis-network:
    external: true